### ISSUE TITLE
Error num_samples=0

### ISSUE THREAD

**Issue by maniappan** [France1/unet-multiclass-pytorch#1]
@France1  I am getting this error when I run the code, am using the sample data provided. what am I doing wrong?
`  File "train.py", line 137, in <module>
    train_loader, val_loader =  make_dataloaders(dir_data, val_ratio, params)
  File "/home/ubuntu/unet-multiclass-pytorch/model/load_data.py", line 63, in make_dataloaders
    train_loader = DataLoader(train_dataset, drop_last=True, **params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 268, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 102, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0`

**Comment by France1** [comment]
`train.py` uses patches of the original images that are not provided in the project. You need to generate those patches using the `Image_preparation.ipynb` notebook. This will generate thousands of patches (that's why they are not provided in the repo) that are used to train the model. 

At the end of the notebook there is a test that let you verify that the model can run using patches that you have just generated. Note that you may also generate new original images using `Image_generation.ipynb`
